version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  swagger-docs:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-docs
    ports:
      - "8080:8080"
    volumes:
      - ./backend/swagger.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
      - BASE_URL=/
      - PORT=8080
    restart: unless-stopped 